apiVersion: v1
kind: Service
metadata:
  name: wordpress-service
  labels:
    app.kubernetes.io/name: wordpress-service
spec:
  ports:
    - port: 80
      nodePort: 32000
  selector:
    app.kubernetes.io/name: wordpress-deployment
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress-deployment
  labels:
    app.kubernetes.io/name: wordpress-deployment
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: wordpress-deployment
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: wordpress-deployment
    spec:
      containers:
        - image: wordpress:latest
          name: wordpress
          env:
            - name: WORDPRESS_DB_HOST
              value: mariadb-service
            - name: WORDPRESS_DB_PASSWORD
              value: mariadbpassword
            - name: WORDPRESS_DB_USER
              value: mariadbuser
            - name: WORDPRESS_DB_NAME
              value: database
          ports:
            - containerPort: 80
              name: web
