apiVersion: apps/v1
kind: Deployment
metadata:
  name: mariadb-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: mariadb-deployment
  template:
    metadata:
      labels:
        app.kubernetes.io/name: mariadb-deployment
    spec:
      containers:
        - name: mariadb
          image: mariadb:latest
          securityContext:
            runAsUser: 1000
            allowPrivilegeEscalation: false
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: password
            - name: MARIADB_USER
              value: mariadbuser
            - name: MARIADB_PASSWORD
              value: mariadbpassword
            - name: MARIADB_DATABASE
              value: database
          ports:
            - containerPort: 3306
              name: sql
          volumeMounts:
            - name: mariadb-storage
              mountPath: /var/lib/mysql
      volumes:
        - name: mariadb-storage
          persistentVolumeClaim:
            claimName: mariadb-pvc
