apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: nginx-deployment
  ports:
    - protocol: TCP
      nodePort: 32000
      targetPort: 80
      port: 80
