apiVersion: v1
kind: Service
metadata:
  name: argocd-server-service
  labels:
    app.kubernetes.io/name: argocd-server-service
spec:
  ports:
    - port: 8080
      nodePort: 32000
  selector:
    app.kubernetes.io/name: argocd-server
  type: NodePort
